# Generated by Django 3.0.8 on 2020-07-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('hot_water_state', models.BooleanField()),
                ('heating_state', models.BooleanField()),
            ],
        ),
    ]
